import { InvestmentProps } from "./Investment";

const investments: InvestmentProps[] = [
	{
		title: "Accountable",
		description: "The New Wave of Verifiable Credit",
		imageURL: "https://www.accountable.capital/",
		imageSource: "investments/accountable.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Agora",
		description: "The Onchain Governance Company",
		imageURL: "https://agora.xyz/",
		imageSource: "investments/agora.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Aligned Layer",
		description: "Fast and Cheap Proof Verification",
		imageURL: "https://alignedlayer.com/",
		imageSource: "investments/aligned.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Astria",
		description: "The Sequencing Layer",
		imageURL: "https://www.astria.org/",
		imageSource: "investments/astria.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Atoma",
		description: "Decentralized AI Private Cloud",
		imageURL: "https://www.atoma.network/",
		imageSource: "investments/atoma.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Berachain",
		description:
			"EVM L1 Turning Liquidity into Security with Proof Of Liquidity",
		imageURL: "https://www.berachain.com/",
		imageSource: "investments/berachain.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "blocksense",
		description: "The ZK Rollup for Verifiable Data and Compute Services",
		imageURL: "https://blocksense.network/",
		imageSource: "investments/blocksense.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Clique",
		description: "TEE Coprocessors for Onchain Applications",
		imageURL: "https://www.clique.tech/",
		imageSource: "investments/clique.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Delta",
		description: "A New Type of Permissionless Network",
		imageURL: "https://www.delta.network/",
		imageSource: "investments/delta.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Eclipse",
		description: "Solana on Ethereum",
		imageURL: "https://www.eclipse.xyz/",
		imageSource: "investments/eclipse.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Exo",
		description: "AI on Any Device",
		imageURL: "https://exolabs.net/",
		imageSource: "investments/exo.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Fabric Cryptography",
		description: "A New Kind of Chip for Cryptography",
		imageURL: "https://www.fabriccryptography.com/",
		imageSource: "investments/fabric.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "FirstBatch",
		description: "Enabling The Path to Safe AGI Through Collaboration",
		imageURL: "https://www.firstbatch.xyz/",
		imageSource: "investments/firstbatch.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Friend",
		description: "AI Companions for Everyone",
		imageURL: "https://friend.com",
		imageSource: "investments/friend.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "GasHawk",
		description: "Save on Ethereum Gas Fees, Automatically and Securely",
		imageURL: "https://www.gashawk.io/",
		imageSource: "investments/gashawk.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "GatlingX",
		description: "GPU-EVM",
		imageURL: "https://x.com/Gatling_X",
		imageSource: "investments/gatlingx.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Gevulot",
		description: "Internet Scale Compute Network for Zero-Knowledge Proofs",
		imageURL: "https://www.gevulot.com/",
		imageSource: "investments/gevulot.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Giza",
		description: "Actionable AI for decentralized applications",
		imageURL: "https://www.gizatech.xyz/",
		imageSource: "investments/giza.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Happy Chain",
		description: "The Simple Happy Game Chain",
		imageURL: "https://linktr.ee/happychaindevs",
		imageSource: "investments/happy_chain.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Herodotus",
		description: "Verifiable Onchain Data and Compute",
		imageURL: "https://herodotus.dev/",
		imageSource: "investments/herodotus.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Inco",
		description: "The Confidentiality Layer",
		imageURL: "https://www.inco.org/",
		imageSource: "investments/inco.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Intuition",
		description: "The Trust Protocol",
		imageURL: "https://herodotus.dev/",
		imageSource: "investments/intuition.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "JokeRace",
		description: "Contests for Communities to Run, Grow, and Monetize",
		imageURL: "https://www.jokerace.io/",
		imageSource: "investments/jokerace.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Lighter",
		description: "Perpetuals with Unmatched Efficiency and Fairness",
		imageURL: "https://lighter.xyz/",
		imageSource: "investments/lighter.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "MegaETH",
		description: "The Real-Time Ethereum Layer 2",
		imageURL: "https://megaeth.systems/",
		imageSource: "investments/megaeth.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Mind Palace",
		description: "Your Personal Time Machine",
		imageURL: "https://www.mindpalace.ai/",
		imageSource: "investments/mind-palace.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Mizu",
		description: "Unified Liquidity Layer",
		imageURL: "https://mizulabs.xyz/",
		imageSource: "investments/mizu.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Mode",
		description:
			"Scaling DeFi through AI agents and Financial Applications",
		imageURL: "https://www.mode.network/",
		imageSource: "investments/mode.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Monad",
		description: "The Most Performant EVM-Compatible Layer 1 Blockchain",
		imageURL: "https://www.monad.xyz/",
		imageSource: "investments/monad.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Morpho",
		description: "The Most Efficient Lending Protocol",
		imageURL: "https://morpho.org/",
		imageSource: "investments/morpho.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Movement",
		description: "Bringing Move to Ethereum and Beyond",
		imageURL: "https://movementlabs.xyz/",
		imageSource: "investments/movement.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Nebra",
		description: "Bringing Proof Singularity to Blockchains",
		imageURL: "https://nebra.one/",
		imageSource: "investments/nebra.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Nillion",
		description: "The Blind Computer",
		imageURL: "https://nillion.com/",
		imageSource: "investments/nillion.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "OnlyDust",
		description: "Open Source Development Funding Platform",
		imageURL: "https://www.onlydust.com/",
		imageSource: "investments/onlydust.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "OpenQ",
		description: "Drive More Value through Developer Relations",
		imageURL: "https://openq.dev/",
		imageSource: "investments/openq.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Phylax",
		description: "Building the Credible Layer",
		imageURL: "https://phylax.watch/",
		imageSource: "investments/phylax.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Pimlico",
		description: "Build with Smart Accounts",
		imageURL: "https://www.pimlico.io/",
		imageSource: "investments/pimlico.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "PIN AI",
		description: "The Open Platform for Personal AI",
		imageURL: "https://pinai.io/",
		imageSource: "investments/pinai.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Pluto",
		description: "Verifiable Web Data for Applications",
		imageURL: "https://pluto.xyz/",
		imageSource: "investments/pluto.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Pragma",
		description: "The Open Infrastructure for Oracles",
		imageURL: "https://www.pragma.build/",
		imageSource: "investments/pragma.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Praxis",
		description: "The Next America Built on the Internet",
		imageURL: "https://www.praxisnation.com/",
		imageSource: "investments/praxis.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Prime Intellect",
		description: "Find Compute. Train Models. Co-Own Intelligence.",
		imageURL: "https://www.primeintellect.ai/",
		imageSource: "investments/prime-intellect.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "PWN",
		description: "DeFi Lending Reimagined",
		imageURL: "https://pwn.xyz/",
		imageSource: "investments/pwn.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Rhinestone",
		description: "Build Powerful Onchain Products with Seamless UX",
		imageURL: "https://www.rhinestone.wtf/",
		imageSource: "investments/rhinestone.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Ritual",
		description: "The World's Sovereign Chain for AI",
		imageURL: "https://ritual.net/",
		imageSource: "investments/ritual.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Sorella",
		description: "Sustainable on-chain Markets",
		imageURL: "https://sorellalabs.xyz/",
		imageSource: "investments/sorella.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Succinct",
		description: "Prove the World's Software",
		imageURL: "https://succinct.xyz/",
		imageSource: "investments/succinct.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Wildcat",
		description: "Fixed Rates, Flexible Everything Else",
		imageURL: "https://wildcat.finance/",
		imageSource: "investments/wildcat.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
	{
		title: "Lucis",
		description:
			"Advanced Diagnostics and Tools for Health Performance and Longevity",
		imageURL: "https://lucis.life/",
		imageSource: "investments/lucis.png",
		imageWidth: ["200px", "200px", "300px", "300px"],
		bgColor: "white",
	},
];

export default investments;
